# Generated by Django 2.1.5 on 2019-02-23 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_username', models.CharField(default='', max_length=32)),
                ('uuid', models.CharField(default='', help_text='Mojang UUID', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='whitelist',
            name='vips',
            field=models.ManyToManyField(related_name='whitelists_joined', to='twitch.VIP'),
        ),
    ]
