# Generated by Django 2.1.5 on 2019-02-24 06:48

from django.db import migrations, models
import twitch.utils


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0003_auto_20190224_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='access_key',
            field=models.CharField(default=twitch.utils.generate_access_key, max_length=32),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
