# Generated by Django 2.1.5 on 2019-02-24 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitch', '0004_auto_20190224_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_username', models.CharField(blank=True, default='', max_length=32)),
                ('uuid', models.CharField(blank=True, default='', help_text='Mojang UUID', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='whitelist',
            name='bans',
            field=models.ManyToManyField(blank=True, related_name='whitelists_banned', to='twitch.Banned'),
        ),
    ]
