# Generated by Django 2.1.5 on 2019-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_username',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(blank=True, default='', help_text='Mojang UUID', max_length=32),
        ),
    ]
